// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message describing ClientConnectorService object.
public struct ClientConnectorService: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Name of resource. The name is ignored during creation.
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. [Output only] Update time stamp.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. User-provided name.
  /// The display name should follow certain format.
  /// * Must be 6 to 30 characters in length.
  /// * Can only contain lowercase letters, numbers, and hyphens.
  /// * Must start with a letter.
  public var displayName: Swift.String = Swift.String()

  /// Required. The details of the ingress settings.
  public var ingress: ClientConnectorService.Ingress? = nil

  /// Required. The details of the egress settings.
  public var egress: ClientConnectorService.Egress? = nil

  /// Output only. The operational state of the ClientConnectorService.
  public var state: ClientConnectorService.State = ClientConnectorService.State()

  /// Initialize a new instance of `ClientConnectorService`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClientConnectorService().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Settings of how to connect to the ClientGateway.
  /// One of the following options should be set.
  public struct Ingress: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    public var ingressConfig: OneOf_IngressConfig? = nil

    /// Initialize a new instance of `Ingress`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Ingress().with { $0.config = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case config = "config"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var ingressConfig: OneOf_IngressConfig? = nil
      let ingressConfigCheckAndSet = {
        if ingressConfig != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'ingressConfig'"))
        }
        ingressConfig = $0
      }
      if let config = try container.decodeIfPresent(
        ClientConnectorService.Ingress.Config?.self, forKey: .config)
      {
        try ingressConfigCheckAndSet(.config(config))
      }
      self.ingressConfig = ingressConfig
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.ingressConfig {
        switch choice {
        case .config(let value):
          try container.encode(value, forKey: .config)
        }
      }
    }

    /// The basic ingress config for ClientGateways.
    public struct Config: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Required. Immutable. The transport protocol used between the client and
      /// the server.
      public var transportProtocol: ClientConnectorService.Ingress.Config.TransportProtocol =
        ClientConnectorService.Ingress.Config.TransportProtocol()

      /// Required. The settings used to configure basic ClientGateways.
      public var destinationRoutes: [ClientConnectorService.Ingress.Config.DestinationRoute] = []

      /// Initialize a new instance of `Config`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Config().with { $0.transportProtocol = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// The setting used to configure ClientGateways.
      /// It is adding routes to the client's routing table
      /// after the connection is established.
      public struct DestinationRoute: Codable, Equatable, GoogleCloudWKT._AnyPackable,
        Sendable
      {
        /// Required. The network address of the subnet
        /// for which the packet is routed to the ClientGateway.
        public var address: Swift.String = Swift.String()

        /// Required. The network mask of the subnet
        /// for which the packet is routed to the ClientGateway.
        public var netmask: Swift.String = Swift.String()

        /// Initialize a new instance of `DestinationRoute`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = DestinationRoute().with { $0.address = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress.Config.DestinationRoute"
        }
        public init(fromAny any: GoogleCloudWKT.`Any`) throws {
          self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWKT.Struct {
          return try GoogleCloudWKT._slowAnySerialize(message: self)
        }
      }

      /// The protocol used to connect to the server.
      public enum TransportProtocol: Codable, Equatable, Sendable {
        /// Default value. This value is unused.
        case unspecified
        /// TCP protocol.
        case tcp
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .tcp: return 1
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "TRANSPORT_PROTOCOL_UNSPECIFIED"
          case .tcp: return "TCP"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TransportProtocol/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "TRANSPORT_PROTOCOL_UNSPECIFIED": self = .unspecified
          case "TCP": self = .tcp
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TransportProtocol/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .tcp
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .tcp: return try container.encode(1)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress.Config"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public enum OneOf_IngressConfig: Codable, Equatable, Sendable {
      /// The basic ingress config for ClientGateways.
      indirect case config(ClientConnectorService.Ingress.Config?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The details of the egress info. One of the following options should be set.
  public struct Egress: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    public var destinationType: OneOf_DestinationType? = nil

    /// Initialize a new instance of `Egress`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Egress().with { $0.peeredVpc = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case peeredVpc = "peeredVpc"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var destinationType: OneOf_DestinationType? = nil
      let destinationTypeCheckAndSet = {
        if destinationType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'destinationType'"))
        }
        destinationType = $0
      }
      if let peeredVpc = try container.decodeIfPresent(
        ClientConnectorService.Egress.PeeredVpc?.self, forKey: .peeredVpc)
      {
        try destinationTypeCheckAndSet(.peeredVpc(peeredVpc))
      }
      self.destinationType = destinationType
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.destinationType {
        switch choice {
        case .peeredVpc(let value):
          try container.encode(value, forKey: .peeredVpc)
        }
      }
    }

    /// The peered VPC owned by the consumer project.
    public struct PeeredVpc: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Required. The name of the peered VPC owned by the consumer project.
      public var networkVpc: Swift.String = Swift.String()

      /// Initialize a new instance of `PeeredVpc`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = PeeredVpc().with { $0.networkVpc = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Egress.PeeredVpc"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public enum OneOf_DestinationType: Codable, Equatable, Sendable {
      /// A VPC from the consumer project.
      indirect case peeredVpc(ClientConnectorService.Egress.PeeredVpc?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Egress"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Represents the different states of a ClientConnectorService.
  public enum State: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// ClientConnectorService is being created.
    case creating
    /// ClientConnectorService is being updated.
    case updating
    /// ClientConnectorService is being deleted.
    case deleting
    /// ClientConnectorService is running.
    case running
    /// ClientConnectorService is down and may be restored in the future.
    /// This happens when CCFE sends ProjectState = OFF.
    case down
    /// ClientConnectorService encountered an error and is in an indeterministic
    /// state.
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .updating: return 2
      case .deleting: return 3
      case .running: return 4
      case .down: return 5
      case .error: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .running: return "RUNNING"
      case .down: return "DOWN"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "RUNNING": self = .running
      case "DOWN": self = .down
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .updating
      case 3: self = .deleting
      case 4: self = .running
      case 5: self = .down
      case 6: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .updating: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .running: return try container.encode(4)
      case .down: return try container.encode(5)
      case .error: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
